### PR TITLE
Ignore ignored tests in pure suites

### LINKED ISSUE #608: `ignore` doesn't work in pure specs / pure tests
```scala
//> using lib "com.disneystreaming::weaver-cats:0.8.0"
import weaver._

object Demo extends FunSuite {
  test("foo".ignore) {
    failure("wat")
  }
}
```

image

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #608

### CODE REVIEW

File: modules/core/src/weaver/suites.scala [hunk 1]
```diff
@@ -67,8 +67,56 @@ abstract class RunnableSuite[F[_]] extends EffectSuite[F] {
   def plan : List[TestName]
   private[weaver] def runUnsafe(args: List[String])(report: TestOutcome => Unit) : Unit =
     effectCompat.unsafeRunSync(run(args)(outcome => effectCompat.effect.delay(report(outcome))))
+
+  def isCI: Boolean = System.getenv("CI") == "true"
+
+  private[weaver] def analyze[Res, F1[_]](testSeq: Seq[(TestName, Res => F1[TestOutcome])], args: List[String]): TagAnalysisResult[Res, F1] = {
```
Comment (kubukoz) [inline modules/core/src/weaver/suites.scala:73]: Happy to move this to a better place if there is one

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
Thanks :)
